const AUTO_ATTACK_MULTIPLIER = 0.85
const COUNTER_ATTACK_MULTIPLIER = 0.3

const DEFAULT_MAX_STATUSES = 9

const FOC_RES_COEFFICIENT = 20

module.exports = {
    AUTO_ATTACK_MULTIPLIER,
    COUNTER_ATTACK_MULTIPLIER,
    DEFAULT_MAX_STATUSES,
    FOC_RES_COEFFICIENT
}
