const AUTO_ATTACK_MULTIPLIER = 0.85
const COUNTER_ATTACK_MULTIPLIER = 0.5

const DEFAULT_MAX_STATUSES = 9

module.exports = {
    AUTO_ATTACK_MULTIPLIER,
    COUNTER_ATTACK_MULTIPLIER,
    DEFAULT_MAX_STATUSES
}
